### ISSUE TITLE
Translating the plotnine gallery page

### ISSUE THREAD

**Issue by machow** [machow/plotnine-docs-demo#3]
Currently, plotnine's gallery page is derived from notebooks of examples that get included in the geom documentation pages.

It's sphinx workflow involves two directives:

* include_example: links to a notebook to insert on the doc page
* gallery: creates the thumbnails on the [gallery page](https://plotnine.readthedocs.io/en/stable/gallery.html)

From what I can tell, the include_example directive sort of registers content that then gets used by the gallery directive ([see code here](https://github.com/has2k1/plotnine/blob/main/doc/sphinxext/examples_and_gallery.py)).

## How could this happen in quarto?

In quarto, a common approach, used on [quarto.org's gallery](https://quarto.org/docs/gallery/), is to use a [gallery.ejs script](https://github.com/quarto-dev/quarto-web/blob/main/docs/gallery/gallery.ejs) along with a gallery.yml config file.

I think for this approach, we'd need to hard-code the pieces from the notebook we want, and then have it do two things:

* output markdown that includes an `{{< embed that_notebook.ipynb#some-tag >}}` shortcode
* link to the page where the example notebook was used (e.g. geom_bar)

## Alternatively

We could use a python script to extract the relevant images from the notebooks and turn them into thumbnails, that live in the gallery folder. Then, the gallery.yml could just point directly to these files (along with a link to the relevant doc page section).

## See also

The [pyshiny-site gallery folder](https://github.com/rstudio/pyshiny-site/tree/main/gallery), with another .ejs script.

**Comment by machow** [comment]
If we can pull the relevant logic out of plotnine's docs/sphinxext (e.g. [`make_thumbnail()`](https://github.com/has2k1/plotnine/blob/main/doc/sphinxext/examples_and_gallery.py#L144)), then we should be able to include thumbnails in the gallery.

**Comment by machow** [comment]
@hamelsmu here are the gallery notebooks plotnine uses:

https://github.com/has2k1/plotnine-examples/tree/main/plotnine_examples/examples

**Comment by hamelsmu** [comment]
@has2k1 can you give me a brief walkthrough of how [this page is generated](https://plotnine.readthedocs.io/en/stable/index.html)?

What notebooks are used exactly?  That part is confusing me a bit!  Thanks!

**Comment by has2k1** [comment]
> @has2k1 can you give me a brief walkthrough of how [this page is generated](https://plotnine.readthedocs.io/en/stable/index.html)?

That is the [index](https://github.com/has2k1/plotnine/blob/2405442dfd59f966ad98a6461ef870ea8e406235/doc/index.rst) page, but I assume you mean the [gallery](https://plotnine.readthedocs.io/en/stable/gallery.html).

The notebooks are kept in a separate in [repo](https://github.com/has2k1/plotnine-examples/). In there is an [examples](https://github.com/has2k1/plotnine-examples/tree/8fc09db529691cd5a8e7e7591ec24081c0bdd0a0/plotnine_examples/examples) directory with notebooks named after objects that we want to document e.g. [geom_segment.ipynb](https://github.com/has2k1/plotnine-examples/blob/main/plotnine_examples/examples/geom_segment.ipynb). The cells in these notebooks can have a magic string `# Gallery Plot` for the output plot of a cell to be included in the gallery.

**How it works**

1. Sphinx uses these templates to document the 
  - [has2k1/plotnine/main/doc/_templates/main.rst](https://raw.githubusercontent.com/has2k1/plotnine/main/doc/_templates/main.rst)
  ```
  {{ fullname }}
  {{ underline }}
  
  .. currentmodule:: {{ module }}
  
  .. auto{{ objtype }}:: {{ objname }}
  
  .. include_examples:: {{ objname }}.ipynb
  ```
  - [has2k1/plotnine/main/doc/_templates/members-example.rst](https://raw.githubusercontent.com/has2k1/plotnine/main/doc/_templates/members-example.rst)
  
  ```
  {{ fullname }}
  {{ underline }}
  
  .. currentmodule:: {{ module }}
  
  {% if objtype == 'class' %}
  .. auto{{ objtype }}:: {{ objname }}
     :members:
  {% else %}
  .. auto{{ objtype }}:: {{ objname }}
  {% endif %}
  
  .. include_examples:: {{ objname }}.ipynb
  ```

2. The templates have a custom directive `include_examples`

  ```
  .. include_examples:: {{ objname }}.ipynb
  ```
  which adds a jupyter notebook (if there is one) to the documentation of the object.

3. That [directive](https://github.com/has2k1/plotnine/blob/2405442dfd59f966ad98a6461ef870ea8e406235/doc/sphinxext/examples_and_gallery.py#L432) is implemented as a sphinx-extension in [plotnine/doc/sphinxext/examples_and_gallery.py](https://github.com/has2k1/plotnine/blob/2405442dfd59f966ad98a6461ef870ea8e406235/doc/sphinxext/examples_and_gallery.py). Looking back the [how it works](https://github.com/has2k1/plotnine/blob/2405442dfd59f966ad98a6461ef870ea8e406235/doc/sphinxext/examples_and_gallery.py#L23) in there is not detailed enough.

4. The extension also implements a [gallery directive](https://github.com/has2k1/plotnine/blob/2405442dfd59f966ad98a6461ef870ea8e406235/doc/sphinxext/examples_and_gallery.py#L23) which is used by [plotnine/doc/gallery.rst](https://github.com/has2k1/plotnine/blob/2405442dfd59f966ad98a6461ef870ea8e406235/doc/gallery.rst) to insert.

5. When the extension is setting up, it converts the jupyter [notebooks to rst](https://github.com/has2k1/plotnine/blob/2405442dfd59f966ad98a6461ef870ea8e406235/doc/sphinxext/examples_and_gallery.py#L434C52-L435C1) with **Examples** added as a title.

6. As the objects are documented, the `include_example` directive inserts the _rst_.

7. At [some point](https://github.com/has2k1/plotnine/blob/2405442dfd59f966ad98a6461ef870ea8e406235/doc/sphinxext/examples_and_gallery.py#L436), the documentation tree has all the Examples. We [traverse](https://github.com/has2k1/plotnine/blob/2405442dfd59f966ad98a6461ef870ea8e406235/doc/sphinxext/examples_and_gallery.py#L170) it and [bundle up](https://github.com/has2k1/plotnine/blob/2405442dfd59f966ad98a6461ef870ea8e406235/doc/sphinxext/examples_and_gallery.py#L92) all images marked for the gallery.

8. At [another point](https://github.com/has2k1/plotnine/blob/2405442dfd59f966ad98a6461ef870ea8e406235/doc/sphinxext/examples_and_gallery.py#L437), we convert those "bundles" to the html that fills in _gallery directive_. 

That is how the gallery gets its content. I hope it is not more confusing!

**Comment by hamelsmu** [comment]
Thanks @has2k1 that helps quite a bit

@machow I have sketched out a [solution that uses plain quarto](https://github.com/hamelsmu/plotnine-examples-quarto/blob/main/plotnine_examples/examples/index.qmd):

[index.qmd](https://github.com/hamelsmu/plotnine-examples-quarto/blob/main/plotnine_examples/examples/index.qmd):
```
---
title: "Plotnine Gallery"
---

::: {.content-block .grid .gap-4}

::: {.g-col-6 .g-col-md-4}
{{< embed PlotnineAnimation.ipynb#spiral >}}
:::

::: {.g-col-6 .g-col-md-4}
{{< embed geom_col.ipynb#two_variable_bar_plot >}}
:::

::: {.g-col-6 .g-col-md-4}
{{< embed geom_density.ipynb#density_curve >}}
:::

::: {.g-col-6 .g-col-md-4}
{{< embed geom_map.ipynb#map >}}
:::

::: {.g-col-6 .g-col-md-4}
{{< embed geom_segment.ipynb#ranges >}}
:::

::: {.g-col-6 .g-col-md-4}
{{< embed geom_segment.ipynb#rank >}}
:::

:::
```

This produces something [that looks like this](https://64a8aa0d07c5a62ad1d7666d--plotnine-quartodoc.netlify.app/):

<img width="1144" alt="image" src="https://github.com/machow/plotnine-docs-demo/assets/1483922/703eefc5-2ef6-4af9-810e-a7762bbccff4">

## Quarto Features used:

1. [Embedding Jupyter notebook cells ](https://quarto.org/docs/authoring/notebook-embed.html)
2. [CSS Grid](https://quarto.org/docs/output-formats/page-layout.html#css-grid)

**Comment by machow** [comment]
Nice! It definitely seems like including everything in a qmd could be a nice alternative to .ejs. I wonder if we could just tuck in the logic for collecting images from notebooks / making thumbnails into the qmd? It seems okay to sidestep the embed shortcode, since the notebooks are also linked from their respective API doc pages.

### Thumbnails

Here's a quick pass at pulling out the thumbnail logic from the sphinx extension:

```python
import nbformat
import io
import base64
from PIL import Image

all_outputs = []

gallery_notebooks = {
    "geom_col": "plotnine-examples/plotnine_examples/examples/geom_col.ipynb"
}
gallery_plots = {
}

for notebook_name, path in gallery_notebooks.items():
    nb = nbformat.read(open("plotnine-examples/plotnine_examples/examples/geom_col.ipynb"), as_version=4)
    for cell in nb["cells"]:
        if "Gallery Plot" in cell.source:
            out_plots = [x for x in cell.outputs if x.output_type == "display_data"]
            if not out_plots:
                raise Exception()

            # currently, I think the gallery only gets the first plot
            gallery_plots[notebook_name] = out_plots[0]

img_str = gallery_plots["geom_col"]["data"]["image/png"]
meta = gallery_plots["geom_col"]["metadata"]["image/png"]

file = io.BytesIO(base64.decodebytes(img_str.encode()))
img = Image.open(file)


# make a thumbnail ------
# taken from https://github.com/has2k1/plotnine/blob/main/doc/sphinxext/examples_and_gallery.py#L68
SOME_THUMBNAIL_PATH = "demo_thumbnail.png"
thumbnail_size = (294, 210)
thumb_size = thumbnail_size[0] * 2, thumbnail_size[1] * 2

# I'm not sure if this just 
im.thumbnail(thumb_size)
im.save(SOME_THUMBNAIL_PATH)

```

### Generating markdown

I wonder if---after dumping the thumbnails somewhere---we could use a qmd cell with `output: markdown` (or `output: asis` or something?) to produce the markdown code (e.g. the `:::` divs) for the gallery.

It definitely seems like the example you gave is a nice alternative to ejs, especially since we could keep everything for making the gallery in one place (and tap python tools to collect things from notebooks)

**Comment by machow** [comment]
Here's the pyshiny site gallery, with html and css we could lift

https://github.com/rstudio/pyshiny-site/blob/main/gallery/

**Comment by has2k1** [comment]
> Let me know what you think!

This is a great starting point and it looks like the [qmd file](https://github.com/hamelsmu/plotnine-examples-quarto/blob/13573032ddd7170c451112c444919f5a48e497eb/plotnine_examples/examples/index.qmd) can be generated dynamically. Indeed, there shouldn't be any custom tooling in quartodoc, only that these efforts should ultimately translate to some kind of documentation in quartodoc.

**Comment by has2k1** [comment]
> Here's the pyshiny site gallery, with html and css we could lift
> 
> https://github.com/rstudio/pyshiny-site/blob/main/gallery/

I cannot see it.

**Comment by hamelsmu** [comment]
Some [pointers by Charles](https://positpbc.slack.com/archives/C01LQETLA7L/p1689113862169149)

![image](https://github.com/machow/plotnine-docs-demo/assets/1483922/1256e981-0399-429c-8d4e-b9ba3b184c05)

**Comment by machow** [comment]
Oh, shoot -- I'll paste the shiny gallery directly, since it's not really a secret

**html (erm ejs)**

```html

<% for (const item of items) { %>

<h2><%- item.category %></h2>

<p><%- item.description %></p>

<div class="list grid" style="column-gap: 30px;">

<% for (const tile of item.tiles) { %>
  <div class="card gallery-entry border-0 rounded-3 g-col-12 g-col-md-6 g-col-lg-4 mb-4" <%= metadataAttrs(tile) %>>
    <a href="<%- tile.href %>" target="_blank">
      <div class="gallery-entry__img-container">
          <img src="<%- tile.thumbnail %>" alt="<%- tile.description %>" class="card-img-top gallery-entry__img" />
      </div>
    </a>
    <a href="<%- tile.href %>" target="_blank">
      <h5 class="link-dark mt-3 mb-2"><%= tile.title %></h5>
    </a>
      <div class="gallery-entry__body p-95">
    
        <% if (tile.publicationdate) { %> 
          <b class="listing-publicationdate"><%= tile.publicationdate %></b>
        <% } %>

        <% if (tile.description) { %> 
          <span class="text-muted"><%= tile.description %></span>
        <% } %>

        <ul>

          <% if (tile.code) { %> 
          <li>
            <a class="view-app" href="<%- tile.href %>" target="_blank">View app</a>
          </li>
          <li>
            <a href="<%- tile.code %>" title="View source code" 
              class="source-code card-text inline-block"
              target="_blank"
              >
              View source
            </a>
          </li>
          <% } %> 

        </ul>
      </div>
    </a>
  </div>
<% } %>

</div>

<% } %>

```

**css**

```css
.gallery-entry {
  display: flex;
}

.link-dark:hover {
  color: #007BC2;
}
.gallery-entry__img-container {
    border: 1px solid #cdd4da;
    height: 185px;
    overflow: hidden;
}

.gallery-entry__img-container img {
    object-fit: contain;
}

.gallery-entry a {
  text-decoration: none;
}

.gallery-entry__body {
  margin-top: 0;
  margin-bottom: 0;
}

.gallery-entry__body ul {
  list-style-type: none;
  padding: 0px;
  margin-bottom: 0;
}
.gallery-entry__body ul li {
  display: inline;
  margin-right: 20px;
}
```

**Comment by hamelsmu** [comment]
Follow up: the most likely solution if we are using quarto is:

1. Generate `_gallery.qmd` with a pre-render script.  The pre render script would be something like this:
```python
from quartodoc import create_gallery
create_gallery(ids=[....])
```

2. In the page you want to include the gallery, use the `includes shortcode`, for example:

```
---
title: Gallery
---

{{< include _gallery.qmd >}}
```

3. The user can also add CSS to make things the way they want, in this case they might add this to `styles.css`:

```css
/* css styles */
.quarto-embed-nb-cell .figure-img {
    height: 250px;
    object-fit: contain;
}
```

**Comment by hamelsmu** [comment]
@machow There is now a [python package named `nb_thumb`](https://fastai.github.io/nb-thumb/) which allows you to easily extract thumbnails from notebook images

It will only work for png and will only work for RGB images

**Comment by hamelsmu** [comment]
I think I'm done https://fastai.github.io/nb-thumb/gallery.html#create-a-gallery

LMK if this will work

**Comment by hamelsmu** [comment]
> This looks great, thanks! Do you mind submitting a PR to this repo, implementing the gallery?

Sure I can work on this next week!

**Comment by hamelsmu** [comment]
I have added the gallery to this repo using `nb-thumb` in this PR https://github.com/machow/plotnine-docs-demo/pull/13
